### PR TITLE
output canvas element itself when outputFormat === 'canvas'

### PR DESCRIPTION
**Pull request by joonhocho**
Having canvas is very useful as you can use it to render directly by adding it to dom, or call toBlob to upload with blob.

### CODE REVIEW

**Comment by Buzut** [comment]
Thank you for your PR. Indeed it can prove useful. 
Could you just update the README to reflect the new option you added?

Also, I realise I forgot to include the package-lock. I'd rather have package-lock than yarn.lock as [Yarn can use package-lock](https://yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/) but not the other way around. So could you either remove the yarn.lock or replace it with package-lock if you happen to also have npm installed (otherwise I'll do it myself).

**Comment by Buzut** [comment]
Awesome. Thank you!

**Comment by joonhocho** [comment]
You're welcome! What do you think about adding promise support?

**Comment by Buzut** [comment]
Would sure be great! I'd be glad if you wanna give it a go.

**Pull request merged**
